const { lastDayOfWeekWithOptions } = require("date-fns/fp")

class ListHolder{
    constructor(lists){
        this.lists = lists
    }

    // add list to holder
    addList(list){
        this.lists.push(list)
    }
    // sort lists - copy items filter
    sortListsByProperty(property){
        this.lists.sort((a, b) => a[property] > b[property] ? 1 : -1);
    }

   // creates a new array removing the list whose title matches the 'name' parameter
    deleteList(name){
        return this.lists.filter(function(list){
            if(list["name"] !== name){
                return true
            }
        })
    }

    // sets the value of the orignal array to the new array generated from 'deleteList()' which will have desired lists removed
    filterOutList(name){
        this.lists = this.deleteList(name)
    }

    // used to 'select' appropriate list when a user is interacting with the DOM
    getList(name){
        // 'filter()' returns an array which one object inside it 
        let temporaryArray = this.lists.filter(list =>{
            return list.name === name
            })
            //'temporaryArray' allows use to just return the object in the array and not the array itself generated by .filter()
            return temporaryArray[0]
    }

}

export{
    ListHolder
}